# docker-compose.yml
version: '3.8'

services:
  api:
    build: .
    image: period-tracker-ml-api
    container_name: period-tracker-api
    ports:
      - "8000:8000"
    environment:
      - PROJECT_NAME=Period Tracker ML API
      - API_V1_STR=/api/v1
      - SECRET_KEY=change_this_in_production_please
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=period_tracker
      - MODEL_STORAGE_PATH=/app/models
    volumes:
      - ./models:/app/models
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:15
    container_name: period-tracker-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=period_tracker
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: period-tracker-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin_password
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: